---
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' }}
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
